#!/bin/bash

# Check if the correct number of arguments is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <simulation_name>"
    exit 1
fi

# Extract the simulation name from the command line argument
SIM_NAME="$1"

# Create a directory for the simulation output
OUTPUT_DIR="sim_${SIM_NAME}"
mkdir -p "$OUTPUT_DIR"
echo "Output directory: $OUTPUT_DIR"

# Set the LAMMPS executable name according to your installation
LAMMPS_EXEC=lmp_serial  # Adjust as necessary, use lmp_mpi for MPI execution if applicable

# Set the filename of your LAMMPS input script
INPUT_SCRIPT="input_cnt.lammps" # default is for cnt tutorial
# INPUT_SCRIPT="$INPUT_SCRIPT.lammps"  #uncomment as necessary
# echo "Input script: $INPUT_SCRIPT"

# Define the log file name within the output directory
OUTPUT_LOG="$OUTPUT_DIR/${SIM_NAME}_simulation.log"
echo "Log file will be written to: $OUTPUT_LOG"

echo "Starting LAMMPS simulation for $SIM_NAME..."
$LAMMPS_EXEC -in $INPUT_SCRIPT -log $OUTPUT_LOG

# Check if the simulation completed successfully
if [ $? -eq 0 ]; then
    echo "LAMMPS simulation completed successfully."
else
    echo "Error: LAMMPS simulation did not complete successfully."
    echo "Check the error details in the output log: $OUTPUT_LOG"
fi

# Move all generated data and files into the output directory
# Replace 'dump.lammpstrj' and 'other_output_files' with actual filenames generated by your simulation
# mv dump.lammpstrj $OUTPUT_DIR/
# mv other_output_files* $OUTPUT_DIR/

echo "LAMMPS simulation script execution finished for $SIM_NAME."
echo "All generated files moved to: $OUTPUT_DIR"

# Optional: Add any post-simulation commands here, e.g., data analysis

echo "All processes for $SIM_NAME completed."
